code:
  local_dir: $CONFIG_DIR/../../
description: AMLT
environment:
  image: waybaba/plightning:v1
  setup:
  - echo "setup start..."
  - export UPRJDIR=/mnt/default/
  - sudo mkdir -p /mnt/storage/output /mnt/storage/data
  - sudo ln -s /mnt/storage/output /output
  - sudo ln -s /mnt/storage/data /data
  - echo "setup finished!"
  username: waybaba
search:
  job_template:
    command:
    - python do_segm.py  batch_size=2 restore_from=/data/models/seg_models/UR/GTA5_source.pth
      no_src_data=true city=cityscapes unc_noise=true tags=[plightning2] task_name=UR  learning_rate={learning_rate_}
    name: RL_Delayed_{experiment_name:s}_{auto:5s}
    sku: G1-P100
  max_trials: 10000
  params:
  - name: learning_rate_
    values:
    - 1.0e-09
    - 0.01
  type: grid
storage:
  input:
    container_name: v-wangwei1
    local_dir: /home/v-wangwei1/
    mount_dir: /mnt/storage
    storage_account_name: resrchvc4data
target:
  name: msrresrchvc
  service: singularity
