code:
  local_dir: $CONFIG_DIR/../../
description: AMLT
environment:
  image: waybaba/plightning:v1
  setup:
  - echo "setup start..."
  - export UPRJDIR=/mnt/default/
  - sudo mkdir -p /mnt/storage/output /mnt/storage/data
  - sudo ln -s /mnt/storage/output /output
  - sudo ln -s /mnt/storage/data /data
  - echo "setup finished!"
  username: waybaba
search:
  job_template:
    command:
    - python do_segm.py  experiment=ur restore_from=/data/models/seg_models/UR/Cityscapes_source_class13.pth
      no_src_data=true city=Rio unc_noise=true debug=false num_rounds=10 tags=[plightning7]
      task_name=UR  batch_size={batch_size_} learning_rate={learning_rate_}
    name: RL_Delayed_{experiment_name:s}_{auto:5s}
    sku: G1-P40
  max_trials: 10000
  params:
  - name: batch_size_
    values:
    - 2
    - 4
  - name: learning_rate_
    values:
    - 0.0
    - 0.01
    - 0.001
    - 0.0001
    - 1.0e-05
    - 1.0e-06
    - 1.0e-07
    - 1.0e-08
  type: grid
storage:
  input:
    container_name: v-wangwei1
    local_dir: /home/v-wangwei1/
    mount_dir: /mnt/storage
    storage_account_name: resrchvc4data
target:
  name: msrresrchvc
  service: singularity
